### ISSUE TITLE
Should K256KeyPair Sign every time return signature with random part?

### ISSUE THREAD

**Issue by arkoc** [chriswill/ripple-netcore#1]
I am working to make offline multisig transaction signing. After couple of tries I found out that K256KeyPair gives same signature for same message. But as I understand it should give new one  (with random part).

**Comment by chriswill** [comment]
This library I ported over from the original one, so I didn't write it myself.  My changes were limited to converting it to .net standard and updating it for the current transaction types.

I haven't done multisig, but every offline transaction I've signed in the past generates the same signature.  For example if you run the sample on the main page the output will remain the same.  I can't see why multisig would be any different.

Do you have any links which would indicate there should be a random part?  I don't believe I've read that in the past.

**Comment by chriswill** [comment]
@arkoc  Thanks for the PR and sorry for the delay in accepting it.  I'll check the code this weekend and merge it and update the nuget as required.
